### ISSUE TITLE
[Feature Request] Accept Text (UTF-8) AES Key and IV source

### ISSUE THREAD

**Issue by pundoo** [string-o-matic/string-o-matic#2]

**Comment by davemorrissey** [comment]
I wanted to have this feature but it's not straightforward. AES requires a 16, 24 or 32 byte key, and a password needs to be converted into a byte key of the right length using a key derivation function.

PBKDF2 is the most commonly used method, but not the only one, and because it has a configurable number of iterations and takes time to calculate, it's complex to implement on the site. All current conversions can be done synchronously without obviously freezing the browser, and the async support I built is broken and disabled.

I chose to leave it up to the user to convert their password to a key of the right length.
